package calculations.runner.kubernetes.template

/**
 * The [JobTemplateProvider] provides a Kubernetes Job Template, containing
 * variables/placeholders that are needed to be substituted to generate a
 * Kubernetes Job Spec. The template can be either loaded from local file,
 * created manually or generated by a tool.
 */
interface JobTemplateProvider {
    /**
     * Get a Kubernetes Job Template, based on which a job definition will be
     * generated
     *
     * @return the template
     */
    fun getTemplate(): String
}